#!/data/data/com.termux/files/usr/bin/sh

cd='\033[1;29m'
de='\033[1;30m'
ef='\033[1;31m'
a='\033[1;32m'
b='\033[1;33m'
c='\033[1;34m'
d='\033[1;35m'
e='\033[1;36m'
f='\033[1;37m'
g='\033[1;38m'
h='\033[1;39m'
i='\033[1;40m'
j='\033[1;41m'
k='\033[1;42m'
l='\033[1;43m'
m='\033[1;44m'
n='\033[1;45m'
o='\033[1;46m'
p='\033[1;47m'
q='\033[1;48m'
r='\033[1;49m'
s='\033[1;50m'
v='\033[1;90m'
w='\033[1;91m'
x='\033[1;92m'
y='\033[1;93m'
z='\033[1;94m'
aa='\033[1;95m'
bb='\033[1;96m'

echo "$x Full Code='‌\‌0‌33‌‌[‌1;‌‌3‌‌2‌m' $x"
cd
echo "$v black type powerful code=90 $v"
cd
echo $w red powerful code=91$w
cd
echo $x green powerful code=92 $x
cd
echo $y yellow powerful code=93$y
cd
echo $z blue powerfull code=94$z
cd
echo $aa pink powerfull code=95$aa
cd
echo $bb sky powerfull code=96$bb
cd
echo "$cd All color code=29 $cd"
echo "$de Black type code=30 $de"
echo "$ef Red code=31 $ef"
echo "$a Green code=32$a"
echo $b Yellow code=33 $b
echo $c Blue code=34 $c
echo $d Pink clde=35 $d
echo $e Sky code=36$e
echo $f White code=37 $f
echo $g White $g
echo $h White $h
echo "$i White $i"
echo $j background red $j
pwd
echo "$k background green $k"
cd
echo "$l background yellow $l"
cd
echo "$m background blue $m"
echo "$n background pink $n"
echo "$o background sky $o"
echo "$p background white $p"
echo "$q  background white $q"
echo "$r white $r"
echo "$s white $s"
echo "$t Green $t"
echo "$u Green $u"
